import Link from "next/link";

import { type Locale, localePath } from "@/i18n/config";
import { ADS_LIVE, CONTACT_EMAIL } from "@/lib/site";
import { LINK, LIST, type LegalText, LegalView } from "@/views/LegalView";

const PROVIDER = "Roger Vergés";
const SOURCE_CODE = "https://github.com/eirasroger/asumisvalinta";
const CC_BY = "https://creativecommons.org/licenses/by/4.0/";
const ODBL = "https://www.openstreetmap.org/copyright";
const CONSUMER_DISPUTES_BOARD = "https://www.kuluttajariita.fi";

const Email = () => (
  <a className={LINK} href={`mailto:${CONTACT_EMAIL}`}>
    {CONTACT_EMAIL}
  </a>
);

const Privacy = ({ locale, children }: { locale: Locale; children: React.ReactNode }) => (
  <Link className={LINK} href={localePath(locale, "/privacy")}>
    {children}
  </Link>
);

const TERMS: Record<Locale, LegalText> = {
  en: {
    title: "Terms of use",
    intro: "These terms govern the use of the Asumisvalinta website and its services.",
    updated: "Last updated 9 October 2026",
    contents: "Contents",
    sections: [
      {
        title: "Scope and acceptance",
        body: (
          <>
            Asumisvalinta (the &quot;service&quot;) is provided by {PROVIDER} (the &quot;provider&quot;). By using the
            service you accept these terms. The processing of personal data is described in the{" "}
            <Privacy locale="en">privacy notice</Privacy>. If you do not accept these terms, do not use the service.
          </>
        ),
      },
      {
        title: "The service",
        body: "The service provides information and calculations on renting, right of occupancy and buying a home in Finland. It is free of charge and requires no registration. The provider may change, restrict, suspend or discontinue the service or any part of it at any time without notice, and does not guarantee that the service is available without interruption or error.",
      },
      {
        title: "No advice",
        body: (
          <>
            The content of the service is general information only. It does not constitute financial, investment,
            tax, legal or real estate advice, nor an offer or a recommendation to rent, buy or sell any property or to
            take out a loan. The content does not take your individual circumstances into account.
            <p className="mt-3">
              You make your decisions independently and at your own risk. Before making a housing or financing
              decision, verify the information and consult a qualified professional where appropriate.
            </p>
          </>
        ),
      },
      {
        title: "Data and calculations",
        body: "Figures are based on official statistics and on the assumptions shown in the service. Where no figure is published for an area, a figure for a larger area is used. Statistics may be revised, delayed or incomplete, and tax and lending rules are applied in a simplified form. Calculation results depend on the figures you enter. The provider does not guarantee the accuracy, completeness or timeliness of any content.",
      },
      {
        title: "The assistant",
        body: (
          <>
            Answers from the assistant are generated by artificial intelligence. They may be inaccurate, incomplete or
            out of date, and should be verified before you rely on them. Questions are processed by third-party AI
            service providers as described in the <Privacy locale="en">privacy notice</Privacy>. Do not include
            personal data or confidential information in your questions.
            <p className="mt-3">
              The number and frequency of questions is limited. The provider may refuse to answer a question and may
              restrict use of the assistant at any time.
            </p>
          </>
        ),
      },
      {
        title: "Acceptable use",
        body: (
          <>
            You may use the service only for lawful purposes and in accordance with these terms. You must not:
            <ul className={`${LIST} mt-3`}>
              <li>disrupt, overload or impair the service or the systems that run it;</li>
              <li>circumvent usage limits, rate limits or security measures;</li>
              <li>
                access the interface of the service by automated means in a way that places an unreasonable load on it,
                or use the interface to provide a competing service;
              </li>
              <li>attempt to make the assistant produce unlawful or harmful content or depart from its purpose;</li>
              <li>introduce malware or attempt to gain unauthorised access to any part of the service;</li>
              <li>present content of the service as advice given or endorsed by the provider.</li>
            </ul>
            <p className="mt-3">The provider may restrict or block access for anyone who breaches these terms.</p>
          </>
        ),
      },
      {
        title: "Intellectual property",
        body: (
          <>
            The texts, guides, graphics and design of the service are owned by the provider or its licensors and are
            protected by copyright. You may view and print content for your personal, non-commercial use. Any other
            reproduction, distribution or modification requires the provider&apos;s prior written consent, except as
            permitted by law, such as quotation with an indication of the source.
            <p className="mt-3">
              The{" "}
              <a className={LINK} href={SOURCE_CODE}>
                source code
              </a>{" "}
              of the service is licensed separately under the PolyForm Noncommercial License 1.0.0.
            </p>
          </>
        ),
      },
      {
        title: "Third-party data",
        body: (
          <>
            The service uses data from third parties, which remain subject to their own terms:
            <ul className={`${LIST} mt-3`}>
              <li>
                Statistics Finland, including Paavo postal code areas, under the{" "}
                <a className={LINK} href={CC_BY}>
                  CC BY 4.0
                </a>{" "}
                licence;
              </li>
              <li>statistics of the European Central Bank;</li>
              <li>the Basic Address File of Posti, under Posti&apos;s terms of use;</li>
              <li>
                map tiles by OpenFreeMap with data from{" "}
                <a className={LINK} href={ODBL}>
                  © OpenStreetMap contributors
                </a>
                .
              </li>
            </ul>
            <p className="mt-3">
              Tax and lending rules are derived from public sources of Finnish authorities. The data suppliers are not
              responsible for the content of the service.
            </p>
          </>
        ),
      },
      {
        title: "Links and advertising",
        body: ADS_LIVE
          ? "The service may contain links to third-party websites and shows ads served by Google. The provider is not responsible for the content, products or services of third parties and does not endorse the advertised products. Cookies used for advertising are described in the privacy notice."
          : "The service may contain links to third-party websites. The provider is not responsible for their content, products or services.",
      },
      {
        title: "Limitation of liability",
        body: (
          <>
            The service is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind. To
            the extent permitted by law, the provider is not liable for any direct or indirect damage or loss arising
            from the use of, or inability to use, the service, including loss arising from decisions made on the basis
            of its content.
            <p className="mt-3">
              This limitation does not apply to damage caused intentionally or through gross negligence, or where
              liability cannot be limited under mandatory law. Nothing in these terms restricts your rights as a
              consumer under mandatory law.
            </p>
          </>
        ),
      },
      {
        title: "Changes to these terms",
        body: "The provider may amend these terms. The current version is published on this page, and the date above shows when it was last updated. Continued use of the service after a change constitutes acceptance of the amended terms.",
      },
      {
        title: "Governing law and disputes",
        body: (
          <>
            These terms are governed by the laws of Finland, without regard to their conflict of law rules. Disputes
            are resolved in the competent district court in Finland. A consumer may also bring an action in the
            district court of their place of residence and refer a dispute to the{" "}
            <a className={LINK} href={CONSUMER_DISPUTES_BOARD}>
              Consumer Disputes Board
            </a>
            .
            <p className="mt-3">
              If any provision of these terms is held invalid, the remaining provisions remain in force.
            </p>
          </>
        ),
      },
      {
        title: "Contact",
        body: (
          <>
            Questions about these terms can be sent to <Email />.
          </>
        ),
      },
    ],
  },
  fi: {
    title: "Käyttöehdot",
    intro: "Näitä ehtoja sovelletaan Asumisvalinta-verkkosivuston ja sen palvelujen käyttöön.",
    updated: "Päivitetty 9.10.2026",
    contents: "Sisällys",
    sections: [
      {
        title: "Soveltamisala ja hyväksyminen",
        body: (
          <>
            Asumisvalinnan (&quot;palvelu&quot;) tarjoaa {PROVIDER} (&quot;palveluntarjoaja&quot;). Käyttämällä
            palvelua hyväksyt nämä ehdot. Henkilötietojen käsittelystä kerrotaan{" "}
            <Privacy locale="fi">tietosuojaselosteessa</Privacy>. Jos et hyväksy ehtoja, älä käytä palvelua.
          </>
        ),
      },
      {
        title: "Palvelu",
        body: "Palvelu tarjoaa tietoa ja laskelmia vuokra-asumisesta, asumisoikeusasumisesta ja asunnon ostamisesta Suomessa. Palvelu on maksuton, eikä sen käyttö edellytä rekisteröitymistä. Palveluntarjoaja voi muuttaa, rajoittaa, keskeyttää tai lopettaa palvelun tai sen osan milloin tahansa ilmoittamatta siitä etukäteen, eikä takaa palvelun toimivan keskeytyksettä tai virheettä.",
      },
      {
        title: "Ei neuvontaa",
        body: (
          <>
            Palvelun sisältö on yleistä tietoa. Se ei ole taloudellista, sijoitus-, vero-, oikeudellista tai
            kiinteistöalan neuvontaa eikä tarjous tai suositus vuokrata, ostaa tai myydä asuntoa tai ottaa lainaa.
            Sisällössä ei oteta huomioon henkilökohtaista tilannettasi.
            <p className="mt-3">
              Teet päätöksesi itsenäisesti ja omalla vastuullasi. Tarkista tiedot ja käänny tarvittaessa
              asiantuntijan puoleen ennen asumista tai rahoitusta koskevaa päätöstä.
            </p>
          </>
        ),
      },
      {
        title: "Tiedot ja laskelmat",
        body: "Luvut perustuvat virallisiin tilastoihin ja palvelussa näytettyihin oletuksiin. Jos alueelle ei ole julkaistu lukua, käytetään laajemman alueen lukua. Tilastoja voidaan korjata, ja ne voivat olla viivästyneitä tai puutteellisia. Vero- ja lainasääntöjä sovelletaan yksinkertaistetusti. Laskelmien tulokset riippuvat syöttämistäsi tiedoista. Palveluntarjoaja ei takaa sisällön oikeellisuutta, täydellisyyttä tai ajantasaisuutta.",
      },
      {
        title: "Avustaja",
        body: (
          <>
            Avustajan vastaukset tuottaa tekoäly. Ne voivat olla virheellisiä, puutteellisia tai vanhentuneita, ja ne
            on tarkistettava ennen kuin niihin luotetaan. Kysymykset käsittelevät ulkopuoliset tekoälypalvelujen
            tarjoajat <Privacy locale="fi">tietosuojaselosteessa</Privacy> kuvatulla tavalla. Älä kirjoita kysymyksiin
            henkilötietoja tai luottamuksellisia tietoja.
            <p className="mt-3">
              Kysymysten määrää ja tiheyttä on rajoitettu. Palveluntarjoaja voi jättää kysymykseen vastaamatta ja
              rajoittaa avustajan käyttöä milloin tahansa.
            </p>
          </>
        ),
      },
      {
        title: "Sallittu käyttö",
        body: (
          <>
            Palvelua saa käyttää vain lainmukaisiin tarkoituksiin ja näiden ehtojen mukaisesti. Et saa:
            <ul className={`${LIST} mt-3`}>
              <li>häiritä, kuormittaa tai heikentää palvelua tai sitä ylläpitäviä järjestelmiä;</li>
              <li>kiertää käyttörajoituksia, pyyntöjen tiheyden rajoituksia tai tietoturvatoimia;</li>
              <li>
                käyttää palvelun rajapintaa automaattisesti tavalla, joka kuormittaa sitä kohtuuttomasti, tai käyttää
                rajapintaa kilpailevan palvelun tarjoamiseen;
              </li>
              <li>yrittää saada avustajaa tuottamaan lainvastaista tai haitallista sisältöä tai poikkeamaan tarkoituksestaan;</li>
              <li>levittää haittaohjelmia tai yrittää päästä luvatta mihinkään palvelun osaan;</li>
              <li>esittää palvelun sisältöä palveluntarjoajan antamana tai hyväksymänä neuvontana.</li>
            </ul>
            <p className="mt-3">Palveluntarjoaja voi rajoittaa tai estää ehtoja rikkovan käyttäjän pääsyn palveluun.</p>
          </>
        ),
      },
      {
        title: "Immateriaalioikeudet",
        body: (
          <>
            Palvelun tekstit, oppaat, grafiikka ja ulkoasu kuuluvat palveluntarjoajalle tai sen lisenssinantajille, ja
            ne on suojattu tekijänoikeudella. Saat katsella ja tulostaa sisältöä henkilökohtaiseen, ei-kaupalliseen
            käyttöön. Muu kopiointi, levittäminen tai muuttaminen edellyttää palveluntarjoajan etukäteen antamaa
            kirjallista lupaa, paitsi lain sallimissa rajoissa, kuten lainattaessa lähde mainiten.
            <p className="mt-3">
              Palvelun{" "}
              <a className={LINK} href={SOURCE_CODE}>
                lähdekoodi
              </a>{" "}
              on lisensoitu erikseen PolyForm Noncommercial License 1.0.0 -lisenssillä.
            </p>
          </>
        ),
      },
      {
        title: "Kolmansien osapuolten aineistot",
        body: (
          <>
            Palvelu käyttää kolmansien osapuolten aineistoja, joihin sovelletaan niiden omia ehtoja:
            <ul className={`${LIST} mt-3`}>
              <li>
                Tilastokeskus, mukaan lukien Paavo-postinumeroalueet,{" "}
                <a className={LINK} href={CC_BY}>
                  CC BY 4.0
                </a>{" "}
                -lisenssillä;
              </li>
              <li>Euroopan keskuspankin tilastot;</li>
              <li>Postin perusosoitetiedosto Postin käyttöehtojen mukaisesti;</li>
              <li>
                OpenFreeMapin karttatiilet, joiden aineisto on peräisin{" "}
                <a className={LINK} href={ODBL}>
                  OpenStreetMapin tekijöiltä
                </a>
                .
              </li>
            </ul>
            <p className="mt-3">
              Vero- ja lainasäännöt perustuvat Suomen viranomaisten julkisiin lähteisiin. Aineistojen toimittajat eivät
              vastaa palvelun sisällöstä.
            </p>
          </>
        ),
      },
      {
        title: "Linkit ja mainonta",
        body: ADS_LIVE
          ? "Palvelu voi sisältää linkkejä kolmansien osapuolten sivustoille, ja palvelussa näytetään Googlen välittämiä mainoksia. Palveluntarjoaja ei vastaa kolmansien osapuolten sisällöstä, tuotteista tai palveluista eikä suosittele mainostettuja tuotteita. Mainonnassa käytettävät evästeet kuvataan tietosuojaselosteessa."
          : "Palvelu voi sisältää linkkejä kolmansien osapuolten sivustoille. Palveluntarjoaja ei vastaa niiden sisällöstä, tuotteista tai palveluista.",
      },
      {
        title: "Vastuunrajoitus",
        body: (
          <>
            Palvelu tarjotaan sellaisenaan ja sellaisena kuin se on saatavilla, ilman minkäänlaisia takuita.
            Palveluntarjoaja ei lain sallimissa rajoissa vastaa välittömistä tai välillisistä vahingoista tai
            menetyksistä, jotka aiheutuvat palvelun käytöstä tai siitä, ettei palvelua voi käyttää, mukaan lukien
            palvelun sisällön perusteella tehdyistä päätöksistä aiheutuvat menetykset.
            <p className="mt-3">
              Rajoitus ei koske tahallisesti tai törkeällä huolimattomuudella aiheutettua vahinkoa eikä tilanteita,
              joissa vastuuta ei voi pakottavan lain nojalla rajoittaa. Nämä ehdot eivät rajoita pakottavan lain mukaisia
              oikeuksiasi kuluttajana.
            </p>
          </>
        ),
      },
      {
        title: "Ehtojen muuttaminen",
        body: "Palveluntarjoaja voi muuttaa näitä ehtoja. Voimassa oleva versio julkaistaan tällä sivulla, ja yllä oleva päivämäärä kertoo, milloin ehtoja on viimeksi päivitetty. Jatkamalla palvelun käyttöä muutoksen jälkeen hyväksyt muutetut ehdot.",
      },
      {
        title: "Sovellettava laki ja riidat",
        body: (
          <>
            Näihin ehtoihin sovelletaan Suomen lakia lukuun ottamatta sen lainvalintasääntöjä. Riidat ratkaistaan
            toimivaltaisessa käräjäoikeudessa Suomessa. Kuluttaja voi nostaa kanteen myös kotipaikkansa käräjäoikeudessa
            ja saattaa riidan{" "}
            <a className={LINK} href={CONSUMER_DISPUTES_BOARD}>
              kuluttajariitalautakunnan
            </a>{" "}
            käsiteltäväksi.
            <p className="mt-3">
              Jos jokin näiden ehtojen määräys todetaan pätemättömäksi, muut määräykset pysyvät voimassa.
            </p>
          </>
        ),
      },
      {
        title: "Yhteystiedot",
        body: (
          <>
            Näitä ehtoja koskevat kysymykset voi lähettää osoitteeseen <Email />.
          </>
        ),
      },
    ],
  },
};

export function TermsView({ locale }: { locale: Locale }) {
  return <LegalView text={TERMS[locale]} />;
}
