import type { Locale } from "@/i18n/config";
import { ADS_LIVE, CONTACT_EMAIL } from "@/lib/site";
import { LINK, type LegalText, LegalView } from "@/views/LegalView";

const PROVIDER = "Roger Vergés";

const Email = () => (
  <a className={LINK} href={`mailto:${CONTACT_EMAIL}`}>
    {CONTACT_EMAIL}
  </a>
);

const TERMS: Record<Locale, LegalText> = {
  en: {
    title: "Terms of use",
    intro: "These terms apply to the use of Asumisvalinta.",
    updated: "Last updated 8 October 2026",
    contents: "Contents",
    sections: [
      {
        title: "The service",
        body: (
          <>
            Asumisvalinta is free to use and is provided by {PROVIDER}. Contact: <Email />. By using the service you
            accept these terms.
          </>
        ),
      },
      {
        title: "Not advice",
        body: "The figures, guides and answers are estimates based on public statistics and the assumptions shown. They are not financial, tax or legal advice.",
      },
      {
        title: "The assistant",
        body: "Answers are generated by AI and can be wrong. Do not include personal data in your questions.",
      },
      {
        title: "Liability",
        body: "The service is provided as is and can change or end at any time. To the extent permitted by law, the provider is not liable for losses arising from its use.",
      },
      {
        title: "Use",
        body: "Do not disrupt the service or get around its limits.",
      },
      ...(ADS_LIVE ? [{ title: "Ads", body: "The service shows ads from Google. Cookies are described in the privacy notice." }] : []),
      {
        title: "Changes",
        body: "These terms can change. The date above shows the current version. Finnish law applies.",
      },
    ],
  },
  fi: {
    title: "Käyttöehdot",
    intro: "Näitä ehtoja sovelletaan Asumisvalinnan käyttöön.",
    updated: "Päivitetty 8.10.2026",
    contents: "Sisällys",
    sections: [
      {
        title: "Palvelu",
        body: (
          <>
            Asumisvalinta on maksuton, ja sen tarjoaa {PROVIDER}. Yhteystiedot: <Email />. Käyttämällä palvelua
            hyväksyt nämä ehdot.
          </>
        ),
      },
      {
        title: "Ei neuvontaa",
        body: "Luvut, oppaat ja vastaukset ovat arvioita, jotka perustuvat julkisiin tilastoihin ja näytettyihin oletuksiin. Ne eivät ole taloudellista, verotuksellista tai oikeudellista neuvontaa.",
      },
      {
        title: "Avustaja",
        body: "Vastaukset tuottaa tekoäly, ja ne voivat olla virheellisiä. Älä kirjoita kysymyksiin henkilötietoja.",
      },
      {
        title: "Vastuu",
        body: "Palvelu tarjotaan sellaisenaan, ja sitä voidaan muuttaa tai se voidaan lopettaa milloin tahansa. Palvelun tarjoaja ei lain sallimissa rajoissa vastaa sen käytöstä aiheutuvista vahingoista.",
      },
      {
        title: "Käyttö",
        body: "Älä häiritse palvelua tai kierrä sen rajoituksia.",
      },
      ...(ADS_LIVE
        ? [{ title: "Mainokset", body: "Palvelussa näytetään Googlen mainoksia. Evästeet kuvataan tietosuojaselosteessa." }]
        : []),
      {
        title: "Muutokset",
        body: "Näitä ehtoja voidaan muuttaa. Yllä oleva päivämäärä kertoo voimassa olevan version. Ehtoihin sovelletaan Suomen lakia.",
      },
    ],
  },
};

export function TermsView({ locale }: { locale: Locale }) {
  return <LegalView text={TERMS[locale]} />;
}
